# Generated by Django 4.2.11 on 2024-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='images')),
                ('Place', models.CharField(max_length=900)),
                ('Days', models.IntegerField()),
                ('Persons', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Trip', models.CharField(max_length=900)),
                ('Description', models.CharField(max_length=900)),
            ],
        ),
    ]
